use `sirv --no-clear` to keep terminal history
sveltejs/template pull request #226
Opened 2021-03-16 07:14 UTC by milahu

currently, the last ~20 lines are removed by sirv, so warnings from rollup are lost
even if that bug in sirv was fixed, i dont want to scroll back my terminal just to see bundler warnings

2021-03-16 07:16 UTC, lukeed requested changes
Please remove the other changes (`src/**`) before this can be considered.
Thanks!

2021-03-16 07:29 UTC, lukeed approved these changes
Thanks! This is fine by me. Let's wait for another opinion

2021-03-16 08:15 UTC, dummdidumm approved these changes

2021-03-24 16:58 UTC, milahu commented
no vetos? ; )

2021-03-24 17:55 UTC, merged